# Generated by Django 4.1.4 on 2022-12-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0002_advert_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
